import { useEffect, useMemo, useState } from "react";

import { LanguageContext } from "./LanguageContextValue";

const DICTIONARY = {
  EN: {
    dashboard: "Dashboard",
    calendar: "Calendar",
    allTrades: "All Trades",
    analytics: "Analytics",
    charts: "Charts",
    accounts: "Accounts",
    settings: "Settings",
    addTrade: "Add Trade",
    overviewTradingPerformance: "Overview of your trading performance.",
    selectAccountPerformance: "Select an account from the header to view its trading performance.",
    loadingTradingData: "Loading trading data...",
    totalTradesDescription: "{wins} wins · {losses} losses",
    winningTradesDescription: "{wins} winning trades",
    netPositivePerformance: "Net positive performance",
    netNegativePerformance: "Net negative performance",
    breakevenTradesDescription: "{count} breakeven trades",
    tradeResults: "Trade Results",
    tradeResultsDescription: "Breakdown of your trade outcomes.",
    pnlSummary: "P&L Summary",
    pnlSummaryDescription: "Your winning and losing performance.",
    psychologyAtEntryDescription: "P&L grouped by your mindset when entering trades.",
    recentTrades: "Recent Trades",
    recentTradesDescription: "Your latest recorded trades.",
    viewAll: "View all",

    date: "Date",
    name: "Name",
    type: "Type",
    trade: "trade",
    psychologyDonutAria: "Psychology at Entry donut chart",
    noPsychologyData: "No psychology data available yet.",
    calendarDescription: "View your trading activity and daily performance.",
    allPairs: "All Pairs",
    allResults: "All Results",
    allStrategies: "All Strategies",
    reset: "Reset",
    today: "Today",
    trades: "Trades",
    monthlyPnlLabel: "Monthly P&L",
    detail: "Detail",
    tradeCount: "{count} trade{plural}",
    unnamedAccount: "Unnamed Account",

    tradingWorkspace: "Trading workspace",
    trackPerformance: "Track your performance and improve your trading",
    logout: "Logout",
    editProfile: "Edit profile",
    logoutConfirmTitle: "Log out of PIPE.ID?",
    logoutConfirmDescription: "You will return to the sign-in page and your current session will end.",
    loggingOut: "Logging out...",
    refresh: "Refresh",
    autoRefresh: "Auto refresh",
    addAccount: "Add Account",
    noAccounts: "No trading accounts yet",
    createAccount: "Create account",

    accountName: "Account Name",
    accountNameRequired: "Account name is required.",
    initialBalanceInvalid: "Initial balance must be a valid number.",
    amountGreaterThanZero: "Amount must be greater than zero.",
    withdrawalExceedsBalance: "Withdrawal cannot exceed the available balance of {balance}.",
    accountType: "Account Type",
    currency: "Currency",
    currencyRequired: "Currency is required.",
    selectCurrency: "Select currency",
    loadingCurrencies: "Loading currencies...",
    currencyFromCatalog: "Currencies are loaded from the active instrument catalog.",
    primaryPair: "Primary Pair (optional)",
    initialBalance: "Initial Balance",
    live: "LIVE",
    demo: "DEMO",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    manageBalance: "Manage Balance",
    deposit: "Deposit",
    withdrawal: "Withdrawal",
    amount: "Amount",
    currentBalance: "Current Balance",
    startingBalance: "Starting Balance",
    tradingPnl: "Trading P&L",
    noTransactions: "No balance transactions yet.",
    selectAccount: "Select account",
    language: "Language",
    lightMode: "Light mode",
    darkMode: "Dark mode",
    noAccountSelected: "Select an account to view journal data",
    accountRequired: "Select an account first",
    allAccounts: "All accounts",

    workspace: "Workspace",
    manageTradingAccounts: "Manage your trading accounts and balance movements.",
    createAccountBeforeTrade: "Create an account before recording a trade.",
    balanceMovement: "Balance Movement",
    chooseDepositWithdrawal:
      "Choose Deposit or Withdrawal first, then enter the amount.",
    change: "Change",
    save: "Save",
    saving: "Saving...",
    recentBalanceMovements: "Recent balance movements",
    depositAmount: "Deposit Amount",
    withdrawalAmount: "Withdrawal Amount",
    renameAccount: "Rename Account",
    deleteAccount: "Delete Account",
    deleteAccountConfirmTitle: "Delete this account?",
    deleteAccountConfirmDescription: "This will permanently delete \"{account}\" and its linked trades and balance movements. This action cannot be undone.",
    deleteAccountFailed: "Failed to delete account.",
    deleting: "Deleting...",
    accountCreated: "Account created successfully.",

    performance: "Performance",
    trading: "Trading",
    psychology: "Psychology",
    totalTrades: "Total Trades",
    winRate: "Win Rate",
    totalPnl: "Total P&L",
    netPnl: "Net P&L",
    profitFactor: "Profit Factor",
    averageWin: "Average Win",
    averageLoss: "Average Loss",
    grossProfit: "Gross Profit",
    grossLoss: "Gross Loss",
    wins: "Wins",
    losses: "Losses",
    breakeven: "Breakeven",
    equityCurve: "Equity Curve",
    monthlyPnl: "Monthly P&L",
    dailyPnl: "Daily P&L",
    pnlByPair: "P&L by Pair",
    pnlByStrategy: "P&L by Strategy",
    pnlBySession: "P&L by Session",
    winRateByStrategy: "Win Rate by Strategy",
    pnlByPsychology: "P&L by Psychology",
    winRateByPsychology: "Win Rate by Psychology",
    performanceByPair: "Performance by Pair",
    performanceByStrategy: "Performance by Strategy",
    performanceBySession: "Performance by Session",
    performanceByPsychology: "Performance by Psychology",
    allTime: "All Time",
    last7Days: "Last 7 Days",
    last30Days: "Last 30 Days",
    last3Months: "Last 3 Months",
    yearToDate: "Year to Date",
    customRange: "Custom Range",
    period: "Period",
    from: "From",
    to: "To",
    thisMonth: "This Month",
    thisYear: "This Year",
    lastMonth: "Last Month",
    chartPeriod: "Chart period",
    chartPageDescription: "Explore your trading performance through clean, interactive visualizations.",
    chartEquityDescription: "Cumulative P&L across your recorded trades.",
    chartDailyDescription: "Profit and loss generated on each trading day.",
    chartPairDescription: "Compare net P&L across your trading pairs.",
    chartPsychologyDescription: "Visualize how your entry mindset is distributed across trades.",
    noChartDataPeriod: "No trades found for this period.",

    pair: "Pair",
    selectPair: "Select pair",
    pairs: "pairs",
    back: "Back",
    legacyPair: "Existing pair",
    searchPair: "Search symbol or pair...",
    loadingInstruments: "Loading instruments...",
    noPairFound: "No matching pair found.",
    instrumentLoadError: "Failed to load instrument catalog.",
    forex: "Forex",
    crypto: "Crypto",
    commodities: "Commodities",
    indices: "Indices",
    stocks: "Stocks",
    futures: "Futures",
    other: "Other",
    account: "Account",
    direction: "Direction",
    result: "Result",
    strategy: "Strategy",
    session: "Session",
    pnl: "P&L",
    psychologyAtEntry: "Psychology at Entry",
    view: "View",
    edit: "Edit",
    delete: "Delete",
    notes: "Notes",
    tradeInformation: "Trade Information",
    priceInformation: "Price Information",
    tradeSetup: "Trade setup",
    priceResult: "Price & result",
    loadingTrade: "Loading trade...",
    tradeNotFound: "Trade not found",
    noNotes: "No notes recorded for this trade.",
    updateTradeDescription:
      "Update the execution, result and psychology recorded for this trade.",
    tradeSaved: "Trade saved successfully.",
    tradeUpdated: "Trade updated successfully.",

    buy: "Buy",
    sell: "Sell",
    win: "Win",
    loss: "Loss",
    neutral: "Neutral",
    greed: "Greed",
    fear: "Fear",
    asia: "Asia",
    london: "London",
    newYork: "New York",
    newYorkAm: "New York AM",
    newYorkPm: "New York PM",
    tokyo: "Tokyo",
    sydney: "Sydney",
    chasingSetup: "Chasing or forcing the setup",
    hesitationRisk: "Hesitation or risk anxiety",
    calmRules: "Calm and rule-based",

    addTradeTitle: "Add Trade",
    addTradeDescription: "Record a new trade in your journal.",
    goToAccounts: "Go to Accounts",
    psychologyQuestion: "How did you feel when entering this trade?",
    saveTrade: "Save Trade",
    fieldRequired: "This field is required.",
    lotRequired: "Lot size is required.",
    lotRange: "Lot size must be between 0.01 and 20.",
    numberInvalid: "Enter a valid number.",
    riskRewardInvalid: "Stop Loss and Take Profit must define a valid risk and reward for this direction.",
    fixFormErrors: "Please fix the highlighted fields before saving.",
    noTradingAccount: "No trading account found",
    noAccountAvailable: "No account available",
    tradeDate: "Trade Date",
    entryPrice: "Entry Price",
    stopLoss: "Stop Loss",
    takeProfit: "Take Profit",
    riskReward: "R:R",
    riskRewardDescription: "Calculated automatically from Entry, Stop Loss and Take Profit.",
    averageRiskReward: "Average R:R",
    lotSize: "Lot Size",
    whyTrade: "Why did you take this trade?",
    updateExecution:
      "Update the execution, result and psychology recorded for this trade.",
    corePosition: "Core information about the position.",
    executionOutcome: "Record the actual execution and outcome.",
    mindsetBefore: "Capture your mindset before the trade was opened.",
    futureReview: "Optional context for your future review.",
    whatHappened: "What happened around this trade?",
    strategyPlaceholder: "Breakout",

    dataManagement: "Data Management",
    reportSubtitle: "Performance summary and journal activity",
    pdfThemeDescription: "PDF follows your current theme.",
    noAnalyticsPeriodData: "No analytics data for this period.",
    generated: "Generated",
    averagePnl: "Average P&L",
    excelExported: "Excel workbook exported successfully.",
    exportExcelFailed: "Failed to export Excel workbook.",
    excelImportComplete: "Import complete: {count} new trade(s) added.",
    accountFilter: "Account filter",
    exportUserScope: "Export is always limited to the signed-in user.",
    activeExportFilter: "Active export filter",
    exportPdfFailed: "Failed to export PDF report.",
    cumulativePnlOrdered: "Cumulative P&L ordered by trade date.",
    netPnlByMonth: "Net P&L grouped by calendar month.",
    highestImpactPairs: "Highest-impact instruments by net P&L.",
    highestImpactStrategies: "Highest-impact strategies by net P&L.",
    winsLosses: "Wins / Losses",
    performanceBreakdown: "Performance Breakdown",
    detailedCategoryAnalysis: "Detailed category analysis",
    psychologyPerformance: "Psychology Performance",
    psychologyDescription: "Trade count, share of trades and net P&L by entry mindset.",
    tradesLabel: "Trades",
    accountsCount: "accounts",
    psychologyImportNote: "Psychology values are normalized to GREED, FEAR or NEUTRAL. Invalid or empty values become NEUTRAL.",
    share: "Share",
    tradeLog: "Trade Log",
    completeExportedTrades: "Complete exported trade records",
    entry: "Entry",
    exit: "Exit",
    lot: "Lot",
    pdfExported: "PDF report exported with charts and analysis.",
    dataManagementDescription:
      "Export a polished report or backup your journal in Excel.",
    includeCharts: "Include charts",
    includeTradeLog: "Include trade log",
    chooseExcelFile: "Choose Excel file",
    importing: "Importing...",
    importData: "Import data",
    pdfPerformanceReport: "PDF Performance Report",
    pdfDescription:
      "Summary, donut charts, equity curve, monthly P&L, pair/strategy analysis, psychology and trade log.",
    excelWorkbook: "Excel Workbook",
    excelDescription:
      "Includes Summary, Trades, Accounts and Psychology sheets with the latest psychology field.",
    pdfContents: "PDF contents",
    pdfContentsDescription:
      "Choose whether the report includes visual charts and the full trade log.",
    excelImport: "Excel Import",
    excelImportDescription:
      "Import the Trades and Accounts sheets. Duplicate trades are skipped.",
    reviewExcelImport: "Review Excel import",

    settingsTitle: "Settings",
    profileDescription: "Update your trading profile information.",
    profilePhoto: "Profile Photo",
    profilePhotoHint: "JPG, PNG, or WebP. Maximum 2 MB.",
    changePhoto: "Change Photo",
    profilePhotoActions: "Open profile photo actions",
    tapPhotoToManage: "Click the profile photo to change, take or delete it.",
    takePhoto: "Take Photo",
    chooseGallery: "Choose from Gallery",
    deletePhoto: "Delete Photo",
    system: "System",
    systemThemeDescription: "System follows your operating system theme.",
    securityDescription: "Change your account password securely.",
    cameraDescription: "Use your front or rear camera.",
    capturedPreview: "Captured preview",
    capture: "Capture",
    changing: "Changing...",
    traderName: "Trader Name",
    journalName: "PIPE.ID",
    settingsJournalName: "Journal Name",
    profile: "Profile",
    security: "Security",
    appearance: "Appearance",
    appearanceDescription: "Choose how PIPE.ID looks.",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    saveProfile: "Save Profile",
    changePassword: "Change Password",
    uploadAvatar: "Upload Avatar",
    removeAvatar: "Remove Avatar",
    enterTraderName: "Enter your trader name",
    enterJournalName: "PIPE.ID",
    enterCurrentPassword: "Enter current password",
    enterNewPassword: "Enter new password",
    confirmNewPassword: "Confirm new password",

    welcomeBack: "Welcome back",
    signInContinue: "Sign in to continue to your journal.",
    signInToContinue: "Sign in to continue to your journal.",
    signIn: "Sign in",
    signingIn: "Signing in...",
    email: "Email",
    password: "Password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    dontHaveAccount: "Don't have an account?",
    createOne: "Create one",
    signUp: "Sign up",
    createWorkspace: "Create your workspace",
    startRecording:
      "Start recording trades and building better habits.",
    createWorkspaceButton: "Create account",
    creatingWorkspace: "Creating workspace...",
    alreadyHaveAccount: "Already have an account?",
    keepImproving: "Keep trading. Keep improving.",
    openNavigation: "Open navigation",
    closeNavigation: "Close navigation",
    accountCreatedCheckEmail:
      "Account created. Check your email to confirm your account, then sign in.",
    passwordLength: "Password must be exactly 8 characters.",
    passwordMin: "Password must be exactly 8 characters.",
    passwordRuleLength: "Exactly 8 characters: 2 uppercase, 2 lowercase, 2 numbers, 2 symbols",
    emailInvalid: "Please enter a valid email address.",
    passwordStrongRequired: "Password must contain exactly 8 characters: 2 uppercase, 2 lowercase, 2 numbers, and 2 symbols.",
    fillAllPasswordFields: "Please fill in all password fields.",
    passwordDifferent: "New password must be different from current password.",
    currentPasswordIncorrect: "Current password is incorrect.",
    passwordChangedSuccessfully: "Password changed successfully.",
    passwordMismatch: "Password confirmation does not match.",
    invalidCredentials: "Email or password is incorrect.",
    passwordStrength: "Password strength",
    weak: "Weak",
    medium: "Medium",
    strong: "Strong",
    fairlyStrong: "Fairly Strong",
    veryStrong: "Very Strong",

    legacyResultBreakeven: "BREAKEVEN",
    legacyTrades: "Trades",
    legacyDate: "Date",
    legacyPeriod: "Period",
    legacyLastMonth: "Last Month",
    legacyEquityCurve: "Equity Curve",
    legacyDailyPnl: "Daily P&L",
    legacyPnlByPair: "P&L by Pair",
    legacyPsychologyAtEntry: "Psychology at Entry",
    legacyTradeOutcome: "Trade Outcome",
    legacyDistributionResults: "Distribution of your trade results.",
    legacyCumulativePnl: "Cumulative P&L over your trades.",
    legacyPnlEachDay: "P&L generated on each trading day.",
    legacyComparePairs: "Compare performance across trading pairs.",
    legacyMindsetDistribution: "Distribution of trades by mindset, with percentage and P&L.",
    legacyViewAllTrades: "View all trades recorded in your journal.",
    legacyNoTrades: "No trades yet",
    legacyStartRecording: "Start recording your trades to build your journal.",
    legacyUnknownAccount: "Unknown Account",
    legacyView: "View",
    legacyBackToAllTrades: "Back to All Trades",
    legacyTradeNotFound: "Trade not found",
    legacyTradeDoesNotExist: "The trade you're looking for does not exist.",
    legacyCompleteTradeInfo: "Complete information about this trade.",
    legacyEntryExitRisk: "Entry, exit and risk management levels.",
    legacyNoStrategy: "No strategy recorded",
    legacyNoNotes: "No notes recorded for this trade.",
    legacyCorePosition: "Core information about the position.",
    legacyPriceResult: "Price & result",
    legacyExecutionOutcome: "Record the actual execution and outcome.",
    legacyMindsetBefore: "Capture your mindset before the trade was opened.",
    legacyFutureReview: "Optional context for your future review.",
    legacyWhatHappened: "What happened around this trade?",
    legacyDataManagement: "Data Management",
    legacyExportBackup: "Export a polished report or backup your journal in Excel.",
    legacyPdfReport: "PDF Performance Report",
    legacyExcelWorkbook: "Excel Workbook",
    legacyPdfContents: "PDF contents",
    legacyChooseReport: "Choose whether the report includes visual charts and the full trade log.",
    legacyIncludeCharts: "Include charts",
    legacyIncludeTradeLog: "Include trade log",
    legacyExcelImport: "Excel Import",
    legacyImportSheets: "Import the Trades and Accounts sheets. Duplicate trades are skipped.",
    legacyChooseExcel: "Choose Excel file",
    legacyReviewImport: "Review Excel import",
    legacyImporting: "Importing...",
    legacyImportData: "Import data",
    legacyAdjustPhoto: "Adjust profile photo",
    legacyPhotoHint: "Square 1:1 • Drag to reposition • Pinch or use the slider to zoom",
    legacyDragAdjust: "Drag to adjust",
    legacyZoom: "Zoom",
    legacyBalanceMovementLower: "Balance movement",
    legacyMyTradingAccount: "My Trading Account",
    legacyPsychologyDonutAria: "Psychology at Entry donut chart",
    legacyClose: "Close",
    legacyProfilePreview: "Profile preview",
    legacyFailedSaveProfile: "Failed to save profile.",
    legacyProfileSaved: "Profile saved successfully.",
    legacyNoImage: "No image selected.",
    legacyImageTypes: "Only JPG, PNG, and WebP images are allowed.",
    legacyImageSize: "Profile image must be smaller than 2 MB.",
    legacyImageUrl: "Profile image uploaded, but public URL could not be created.",
    legacyPhotoUpdated: "Profile photo updated successfully.",
    legacyUploadFailed: "Failed to upload profile photo.",
    legacyCameraPermission: "Camera permission was denied. Please allow camera access in your browser.",
    legacyNoCamera: "No camera was found on this device.",
    legacyCameraBusy: "Camera is already being used by another application.",
    legacyCaptureFailed: "Failed to capture photo.",
    legacyPhotoDeleted: "Profile photo deleted successfully.",
    legacyDeleteFailed: "Failed to delete profile photo.",
    legacyPasswordDifferent: "New password must be different from current password.",
    legacyPasswordMismatch: "New passwords do not match.",
    legacyCurrentPasswordIncorrect: "Current password is incorrect.",
    legacyPasswordChanged: "Password changed successfully.",



    "Account": "Account",
    "Detail": "Detail",
    "Security": "Security",
    "Recovery & Contact": "Recovery & Contact",
    "Keep your backup contact information up to date.": "Keep your backup contact information up to date.",
    "Backup Email": "Backup Email",
    "Only Gmail addresses ending in @gmail.com are accepted.": "Only Gmail addresses ending in @gmail.com are accepted.",
    "Country": "Country",
    "Phone / WhatsApp": "Phone / WhatsApp",
    "Numbers only. Country code is selected separately.": "Numbers only. Country code is selected separately.",
    "Change Email": "Change Email",
    "Verify your current password before changing the sign-in email.": "Verify your current password before changing the sign-in email.",
    "Current Email": "Current Email",
    "New Gmail": "New Gmail",
    "Current Password": "Current Password",
    "Change Password": "Change Password",
    "Verify your current password before setting a new one.": "Verify your current password before setting a new one.",
    "Password strength": "Password strength",
    "Profile": "Profile",
    "Appearance": "Appearance",
    "Data": "Data",
    "Trader name, journal name, and profile photo.": "Trader name, journal name, and profile photo.",
    "Theme and automatic refresh preferences.": "Theme and automatic refresh preferences.",
    "Password, email, backup email, and phone / WhatsApp.": "Password, email, backup email, and phone / WhatsApp.",
    "Data Management": "Data Management",
    "Theme": "Theme",
    "Choose how PIPE.ID looks on your device.": "Choose how PIPE.ID looks on your device.",
    "Light": "Light",
    "Dark": "Dark",
    "System": "System",
    "Saving theme...": "Saving theme...",
    "Theme preference": "Theme preference",
    "Your preference is saved to your account.": "Your preference is saved to your account.",
    "Currently enabled.": "Currently enabled.",
    "Currently disabled.": "Currently disabled.",
    "On": "On",
    "Off": "Off",
    "Auto Refresh": "Auto Refresh",
    "Automatically refresh journal data at a selected interval.": "Automatically refresh journal data at a selected interval.",
    "Enable Auto Refresh": "Enable Auto Refresh",
    "Refresh Interval": "Refresh Interval",
    "15 seconds": "15 seconds",
    "30 seconds": "30 seconds",
    "1 minute": "1 minute",
    "5 minutes": "5 minutes",
    "Saving...": "Saving...",
    "Save Profile": "Save Profile",
    "Profile saved successfully.": "Profile saved successfully.",
    "Failed to save profile.": "Failed to save profile.",
    "Profile Photo": "Profile Photo",
    "Change Photo": "Change Photo",
    "Take Photo": "Take Photo",
    "Choose from Gallery": "Choose from Gallery",
    "Delete Photo": "Delete Photo",
    "Profile photo updated successfully.": "Profile photo updated successfully.",
    "Failed to upload profile photo.": "Failed to upload profile photo.",
    "Profile photo removed successfully.": "Profile photo removed successfully.",
    "Failed to remove profile photo.": "Failed to remove profile photo.",
    "Camera permission was denied. Please allow camera access in your browser.": "Camera permission was denied. Please allow camera access in your browser.",
    "No camera was found on this device.": "No camera was found on this device.",
    "Camera is already being used by another application.": "Camera is already being used by another application.",
    "Failed to capture photo.": "Failed to capture photo.",
    "Only JPG, PNG, and WebP images are allowed.": "Only JPG, PNG, and WebP images are allowed.",
    "Profile image must be smaller than 12 MB.": "Profile image must be smaller than 12 MB.",
    "No image selected.": "No image selected.",
    "Close camera": "Close camera",
    "Switch camera": "Switch camera",
    "Capture photo": "Capture photo",
    "Uploading...": "Uploading...",
    "Upload": "Upload",
    "Adjust profile photo": "Adjust profile photo",
    "Zoom photo": "Zoom photo",
    "Email must use lowercase letters and end in @gmail.com.": "Email must use lowercase letters and end in @gmail.com.",
    "Registration successful. Check your email to confirm your account.": "Registration successful. Check your email to confirm your account.",
    "Loading trades...": "Loading trades...",
    "WIN": "WIN",
    "LOSS": "LOSS",
    "BREAKEVEN": "BREAKEVEN",
    "Loss akan otomatis disimpan sebagai nilai negatif.": "Loss akan otomatis disimpan sebagai nilai negatif.",
    "Profit akan otomatis disimpan sebagai nilai positif.": "Profit akan otomatis disimpan sebagai nilai positif.",
    "Break-even otomatis disimpan sebagai 0.": "Break-even otomatis disimpan sebagai 0.",
    "Security contact information saved successfully.": "Security contact information saved successfully.",
    "Email changed successfully.": "Email changed successfully.",
    "Failed to load security settings.": "Failed to load security settings.",
    "Backup email must use lowercase letters and end in @gmail.com.": "Backup email must use lowercase letters and end in @gmail.com.",
    "Backup email must be different from your registered email.": "Backup email must be different from your registered email.",
    "Phone / WhatsApp number must contain 11 to 12 digits.": "Phone / WhatsApp number must contain 11 to 12 digits.",
    "New email must use lowercase letters and end in @gmail.com.": "New email must use lowercase letters and end in @gmail.com.",
    "The new email is the same as your current email.": "The new email is the same as your current email.",
    "The new email must be different from your backup email.": "The new email must be different from your backup email.",
    "Enter your current password before changing your email.": "Enter your current password before changing your email.",
    "Current password": "Current password",
    "New password": "New password",
    "Confirm new password": "Confirm new password",
    "Email": "Email",
    "Phone / WhatsApp must contain 11 to 12 digits.": "Phone / WhatsApp must contain 11 to 12 digits.",
    "Save Contact": "Save Contact",
    "Update": "Update",
    "Updating...": "Updating...",
    "Use lowercase letters only and a Gmail address ending in @gmail.com.": "Use lowercase letters only and a Gmail address ending in @gmail.com.",
    "This is the same as your current email.": "This is the same as your current email.",
    "This email is already your backup email.": "This email is already your backup email.",
    "Current password is required.": "Current password is required.",
    "Failed to change password.": "Failed to change password.",
    "Theme saved successfully.": "Theme saved successfully.",
    "Failed to save theme.": "Failed to save theme.",
    "Trade": "Trade",
    "Trades": "Trades",
    "Unknown Account": "Unknown Account",
    "Unspecified": "Unspecified",
    "BREAKEVEN": "Breakeven",
    "Trade with clarity.": "Trade with clarity.",
    "Keep your trades, performance and psychology in one focused workspace.":
      "Keep your trades, performance and psychology in one focused workspace.",
    "Trading Journal · Private workspace":
      "PIPE.ID · Private workspace",
    "Loading trades...": "Loading trades...",
    "Select an account to view journal data":
      "Select an account to view journal data",
    "Select an account first": "Select an account first",
    "All Accounts": "All Accounts",
    "All Pairs": "All Pairs",
    "All Results": "All Results",
    "All Strategies": "All Strategies",
    "Create account before recording a trade.":
      "Create account before recording a trade.",
    "No trading account found": "No trading account found",
    "No account available": "No account available",
    "Loading...": "Loading...",
    "Trade not found.": "Trade not found.",
    "Trade not found": "Trade not found",
    "No notes recorded for this trade.":
      "No notes recorded for this trade.",
    "Capture": "Capture",
    "Review Excel import": "Review Excel import",
    "Cancel": "Cancel",
    "Change": "Change",
    "Save": "Save",
    "Saving...": "Saving..."
  },

  ID: {
    dashboard: "Dasbor",
    calendar: "Kalender",
    allTrades: "Semua Trade",
    analytics: "Analitik",
    charts: "Grafik",
    accounts: "Akun",
    settings: "Pengaturan",
    addTrade: "Tambah Trade",
    overviewTradingPerformance: "Ringkasan performa trading Anda.",
    selectAccountPerformance: "Pilih akun dari header untuk melihat performa tradingnya.",
    loadingTradingData: "Memuat data trading...",
    totalTradesDescription: "{wins} menang · {losses} kalah",
    winningTradesDescription: "{wins} trade menang",
    netPositivePerformance: "Performa bersih positif",
    netNegativePerformance: "Performa bersih negatif",
    breakevenTradesDescription: "{count} trade impas",
    tradeResults: "Hasil Trade",
    tradeResultsDescription: "Rincian hasil trade Anda.",
    pnlSummary: "Ringkasan P&L",
    pnlSummaryDescription: "Performa profit dan loss Anda.",
    psychologyAtEntryDescription: "P&L berdasarkan kondisi psikologis Anda saat entry.",
    recentTrades: "Trade Terbaru",
    recentTradesDescription: "Trade yang baru saja Anda catat.",
    viewAll: "Lihat semua",

    date: "Tanggal",
    name: "Nama",
    type: "Tipe",
    trade: "trade",
    psychologyDonutAria: "Diagram donut psikologi saat entry",
    noPsychologyData: "Belum ada data psikologi.",
    calendarDescription: "Lihat aktivitas trading dan performa harian Anda.",
    allPairs: "Semua Pair",
    allResults: "Semua Hasil",
    allStrategies: "Semua Strategi",
    reset: "Reset",
    today: "Hari Ini",
    trades: "Trade",
    monthlyPnlLabel: "P&L Bulanan",
    detail: "Detail",
    tradeCount: "{count} trade{plural}",
    unnamedAccount: "Akun Tanpa Nama",

    tradingWorkspace: "Ruang Kerja Trading",
    trackPerformance:
      "Pantau performa dan tingkatkan kemampuan trading Anda",
    logout: "Keluar",
    editProfile: "Edit profil",
    logoutConfirmTitle: "Keluar dari PIPE.ID?",
    logoutConfirmDescription: "Anda akan kembali ke halaman masuk dan sesi saat ini akan diakhiri.",
    loggingOut: "Sedang keluar...",
    refresh: "Muat Ulang",
    autoRefresh: "Penyegaran otomatis",
    addAccount: "Tambah Akun",
    noAccounts: "Belum ada akun trading",
    createAccount: "Buat Akun",

    accountName: "Nama Akun",
    accountNameRequired: "Nama akun wajib diisi.",
    initialBalanceInvalid: "Saldo awal harus berupa angka yang valid.",
    amountGreaterThanZero: "Jumlah harus lebih besar dari nol.",
    withdrawalExceedsBalance: "Penarikan tidak boleh melebihi saldo tersedia sebesar {balance}.",
    accountType: "Jenis Akun",
    currency: "Mata Uang",
    currencyRequired: "Mata uang wajib diisi.",
    selectCurrency: "Pilih mata uang",
    loadingCurrencies: "Memuat mata uang...",
    currencyFromCatalog: "Mata uang diambil dari katalog instrumen aktif.",
    primaryPair: "Pair Utama (opsional)",
    initialBalance: "Saldo Awal",
    live: "LIVE",
    demo: "DEMO",
    saveChanges: "Simpan Perubahan",
    cancel: "Batal",
    manageBalance: "Kelola Saldo",
    deposit: "Setoran",
    withdrawal: "Penarikan",
    amount: "Jumlah",
    currentBalance: "Saldo Saat Ini",
    startingBalance: "Saldo Awal",
    tradingPnl: "P&L Trading",
    noTransactions: "Belum ada transaksi saldo.",
    selectAccount: "Pilih Akun",
    language: "Bahasa",
    lightMode: "Mode terang",
    darkMode: "Mode gelap",
    noAccountSelected:
      "Pilih akun untuk melihat data jurnal",
    accountRequired: "Pilih akun terlebih dahulu",
    allAccounts: "Semua Akun",

    workspace: "Ruang Kerja",
    manageTradingAccounts:
      "Kelola akun trading dan pergerakan saldo Anda.",
    createAccountBeforeTrade:
      "Buat akun terlebih dahulu sebelum mencatat trade.",
    balanceMovement: "Pergerakan Saldo",
    chooseDepositWithdrawal:
      "Pilih Setoran atau Penarikan terlebih dahulu, lalu masukkan jumlahnya.",
    change: "Ubah",
    save: "Simpan",
    saving: "Menyimpan...",
    recentBalanceMovements: "Riwayat Pergerakan Saldo",
    depositAmount: "Jumlah Setoran",
    withdrawalAmount: "Jumlah Penarikan",
    renameAccount: "Ganti Nama Akun",
    deleteAccount: "Hapus Akun",
    deleteAccountConfirmTitle: "Hapus akun ini?",
    deleteAccountConfirmDescription: "Akun \"{account}\" beserta trade dan pergerakan saldo yang terkait akan dihapus permanen. Tindakan ini tidak dapat dibatalkan.",
    deleteAccountFailed: "Gagal menghapus akun.",
    deleting: "Menghapus...",
    accountCreated: "Akun berhasil dibuat.",

    performance: "Performa",
    trading: "Trading",
    psychology: "Psikologi",
    totalTrades: "Total Trade",
    winRate: "Tingkat Kemenangan",
    totalPnl: "Total P&L",
    netPnl: "P&L Bersih",
    profitFactor: "Faktor Profit",
    averageWin: "Rata-rata Profit",
    averageLoss: "Rata-rata Loss",
    grossProfit: "Profit Bruto",
    grossLoss: "Loss Bruto",
    wins: "Menang",
    losses: "Kalah",
    breakeven: "Impas",
    equityCurve: "Kurva Equity",
    monthlyPnl: "P&L Bulanan",
    dailyPnl: "P&L Harian",
    pnlByPair: "P&L per Pair",
    pnlByStrategy: "P&L per Strategi",
    pnlBySession: "P&L per Sesi",
    winRateByStrategy:
      "Tingkat Kemenangan per Strategi",
    pnlByPsychology: "P&L per Psikologi",
    winRateByPsychology:
      "Tingkat Kemenangan per Psikologi",
    performanceByPair: "Performa per Pair",
    performanceByStrategy: "Performa per Strategi",
    performanceBySession: "Performa per Sesi",
    performanceByPsychology: "Performa per Psikologi",
    allTime: "Sepanjang Waktu",
    last7Days: "7 Hari Terakhir",
    last30Days: "30 Hari Terakhir",
    last3Months: "3 Bulan Terakhir",
    yearToDate: "Tahun Berjalan",
    customRange: "Rentang Kustom",
    period: "Periode",
    from: "Dari",
    to: "Sampai",
    thisMonth: "Bulan Ini",
    thisYear: "Tahun Ini",
    lastMonth: "Bulan Lalu",
    chartPeriod: "Periode grafik",
    chartPageDescription: "Jelajahi performa trading Anda melalui visualisasi yang bersih dan interaktif.",
    chartEquityDescription: "P&L kumulatif dari seluruh trade yang tercatat.",
    chartDailyDescription: "Profit dan loss yang dihasilkan pada setiap hari trading.",
    chartPairDescription: "Bandingkan P&L bersih berdasarkan pair trading.",
    chartPsychologyDescription: "Lihat distribusi kondisi psikologis Anda saat entry.",
    noChartDataPeriod: "Tidak ada trade pada periode ini.",

    pair: "Pair",
    selectPair: "Pilih pair",
    pairs: "pair",
    back: "Kembali",
    legacyPair: "Pair lama",
    searchPair: "Cari symbol atau pair...",
    loadingInstruments: "Memuat instrument...",
    noPairFound: "Pair yang dicari tidak ditemukan.",
    instrumentLoadError: "Gagal memuat katalog instrument.",
    forex: "Forex",
    crypto: "Crypto",
    commodities: "Komoditas",
    indices: "Indeks",
    stocks: "Saham",
    futures: "Futures",
    other: "Lainnya",
    account: "Akun",
    direction: "Arah",
    result: "Hasil",
    strategy: "Strategi",
    session: "Sesi",
    pnl: "P&L",
    psychologyAtEntry: "Psikologi Saat Entry",
    view: "Lihat",
    edit: "Ubah",
    delete: "Hapus",
    notes: "Catatan",
    tradeInformation: "Informasi Trade",
    priceInformation: "Informasi Harga",
    tradeSetup: "Setup Trade",
    priceResult: "Harga & Hasil",
    loadingTrade: "Memuat trade...",
    tradeNotFound: "Trade tidak ditemukan",
    noNotes: "Belum ada catatan untuk trade ini.",
    updateTradeDescription:
      "Perbarui eksekusi, hasil, dan psikologi yang dicatat untuk trade ini.",
    tradeSaved: "Trade berhasil disimpan.",
    tradeUpdated: "Trade berhasil diperbarui.",

    buy: "Beli",
    sell: "Jual",
    win: "Untung",
    loss: "Rugi",
    neutral: "Netral",
    greed: "Serakah",
    fear: "Takut",
    asia: "Asia",
    london: "London",
    newYork: "New York",
    newYorkAm: "New York AM",
    newYorkPm: "New York PM",
    tokyo: "Tokyo",
    sydney: "Sydney",
    chasingSetup: "Mengejar atau memaksakan setup",
    hesitationRisk: "Ragu atau cemas terhadap risiko",
    calmRules: "Tenang dan mengikuti aturan",

    addTradeTitle: "Tambah Trade",
    addTradeDescription: "Catat trade baru ke dalam jurnal Anda.",
    goToAccounts: "Ke Akun",
    psychologyQuestion: "Bagaimana perasaan Anda saat memasuki trade ini?",
    saveTrade: "Simpan Trade",
    fieldRequired: "Kolom ini wajib diisi.",
    lotRequired: "Lot size wajib diisi.",
    lotRange: "Lot size harus antara 0.01 dan 20.",
    numberInvalid: "Masukkan angka yang valid.",
    riskRewardInvalid: "Stop Loss dan Take Profit harus membentuk risiko dan reward yang valid untuk arah ini.",
    fixFormErrors: "Perbaiki kolom yang ditandai sebelum menyimpan.",
    noTradingAccount: "Akun trading tidak ditemukan",
    noAccountAvailable: "Tidak ada akun tersedia",
    tradeDate: "Tanggal Trade",
    entryPrice: "Harga Entry",
    stopLoss: "Stop Loss",
    takeProfit: "Take Profit",
    riskReward: "R:R",
    riskRewardDescription: "Dihitung otomatis dari Entry, Stop Loss, dan Take Profit.",
    averageRiskReward: "Rata-rata R:R",
    lotSize: "Lot Size",
    whyTrade: "Mengapa Anda mengambil trade ini?",
    updateExecution:
      "Perbarui eksekusi, hasil, dan psikologi yang dicatat untuk trade ini.",
    corePosition: "Informasi utama mengenai posisi.",
    executionOutcome: "Catat eksekusi dan hasil aktual.",
    mindsetBefore: "Catat kondisi psikologis Anda sebelum trade dibuka.",
    futureReview: "Konteks tambahan untuk evaluasi di masa mendatang.",
    whatHappened: "Apa yang terjadi pada trade ini?",
    strategyPlaceholder: "Breakout",

    dataManagement: "Manajemen Data",
    reportSubtitle: "Ringkasan performa dan aktivitas jurnal",
    pdfThemeDescription: "PDF mengikuti tema yang sedang digunakan.",
    noAnalyticsPeriodData: "Tidak ada data analitik untuk periode ini.",
    generated: "Dibuat",
    averagePnl: "Rata-rata P&L",
    excelExported: "Workbook Excel berhasil diekspor.",
    exportExcelFailed: "Gagal mengekspor workbook Excel.",
    excelImportComplete: "Impor selesai: {count} trade baru ditambahkan.",
    accountFilter: "Filter akun",
    exportUserScope: "Ekspor selalu dibatasi pada user yang sedang masuk.",
    activeExportFilter: "Filter ekspor aktif",
    exportPdfFailed: "Gagal mengekspor laporan PDF.",
    cumulativePnlOrdered: "P&L kumulatif berdasarkan tanggal trade.",
    netPnlByMonth: "P&L bersih berdasarkan bulan kalender.",
    highestImpactPairs: "Pair dengan dampak terbesar berdasarkan P&L bersih.",
    highestImpactStrategies: "Strategi dengan dampak terbesar berdasarkan P&L bersih.",
    winsLosses: "Menang / Kalah",
    performanceBreakdown: "Rincian Performa",
    detailedCategoryAnalysis: "Analisis kategori secara detail",
    psychologyPerformance: "Performa Psikologi",
    psychologyDescription: "Jumlah trade, persentase, dan P&L bersih berdasarkan psikologi saat entry.",
    tradesLabel: "Trade",
    accountsCount: "akun",
    psychologyImportNote: "Nilai psikologi dinormalisasi menjadi GREED, FEAR, atau NEUTRAL. Nilai kosong atau tidak valid akan menjadi NEUTRAL.",
    share: "Persentase",
    tradeLog: "Log Trade",
    completeExportedTrades: "Seluruh data trade yang diekspor",
    entry: "Entry",
    exit: "Exit",
    lot: "Lot",
    pdfExported: "Laporan PDF berhasil diekspor dengan grafik dan analisis.",
    dataManagementDescription:
      "Ekspor laporan rapi atau cadangkan jurnal Anda ke Excel.",
    includeCharts: "Sertakan grafik",
    includeTradeLog: "Sertakan log trade",
    chooseExcelFile: "Pilih file Excel",
    importing: "Mengimpor...",
    importData: "Impor Data",
    pdfPerformanceReport: "Laporan Performa PDF",
    pdfDescription:
      "Ringkasan, grafik donut, equity curve, P&L bulanan, analisis pair/strategi, psikologi, dan log trade.",
    excelWorkbook: "Workbook Excel",
    excelDescription:
      "Berisi sheet Summary, Trades, Accounts, dan Psychology dengan field psikologi terbaru.",
    pdfContents: "Isi PDF",
    pdfContentsDescription:
      "Pilih apakah laporan menyertakan grafik visual dan seluruh log trade.",
    excelImport: "Impor Excel",
    excelImportDescription:
      "Impor sheet Trades dan Accounts. Trade duplikat akan dilewati.",
    reviewExcelImport: "Tinjau Impor Excel",

    settingsTitle: "Pengaturan",
    profileDescription: "Perbarui informasi profil trading Anda.",
    profilePhoto: "Foto Profil",
    profilePhotoHint: "JPG, PNG, atau WebP. Maksimal 2 MB.",
    changePhoto: "Ganti Foto",
    profilePhotoActions: "Buka pilihan foto profil",
    tapPhotoToManage: "Klik foto profil untuk mengganti, mengambil, atau menghapus foto.",
    takePhoto: "Ambil Foto",
    chooseGallery: "Pilih dari Galeri",
    deletePhoto: "Hapus Foto",
    system: "Sistem",
    systemThemeDescription: "Sistem mengikuti tema perangkat Anda.",
    securityDescription: "Ganti password akun Anda dengan aman.",
    cameraDescription: "Gunakan kamera depan atau belakang.",
    capturedPreview: "Pratinjau hasil foto",
    capture: "Ambil Foto",
    changing: "Mengubah...",
    traderName: "Nama Trader",
    journalName: "PIPE.ID",
    settingsJournalName: "Nama Jurnal",
    profile: "Profil",
    security: "Keamanan",
    appearance: "Tampilan",
    appearanceDescription: "Pilih tampilan PIPE.ID.",
    theme: "Tema",
    light: "Terang",
    dark: "Gelap",
    currentPassword: "Password Saat Ini",
    newPassword: "Password Baru",
    confirmPassword: "Konfirmasi Password",
    saveProfile: "Simpan Profil",
    changePassword: "Ganti Password",
    uploadAvatar: "Unggah Foto Profil",
    removeAvatar: "Hapus Foto Profil",
    enterTraderName: "Masukkan nama trader",
    enterJournalName: "PIPE.ID",
    enterCurrentPassword: "Masukkan password saat ini",
    enterNewPassword: "Masukkan password baru",
    confirmNewPassword: "Konfirmasi password baru",

    welcomeBack: "Selamat Datang Kembali",
    signInContinue:
      "Masuk untuk melanjutkan ke jurnal Anda.",
    signInToContinue:
      "Masuk untuk melanjutkan ke jurnal Anda.",
    signIn: "Masuk",
    signingIn: "Sedang masuk...",
    email: "Email",
    password: "Password",
    showPassword: "Tampilkan password",
    hidePassword: "Sembunyikan password",
    dontHaveAccount: "Belum punya akun?",
    createOne: "Buat akun",
    signUp: "Daftar",
    createWorkspace: "Buat Ruang Kerja",
    startRecording:
      "Mulai mencatat trade dan membangun kebiasaan yang lebih baik.",
    createWorkspaceButton: "Buat Akun",
    creatingWorkspace: "Membuat ruang kerja...",
    alreadyHaveAccount: "Sudah punya akun?",
    keepImproving: "Terus trading. Terus berkembang.",
    openNavigation: "Buka navigasi",
    closeNavigation: "Tutup navigasi",
    accountCreatedCheckEmail:
      "Akun berhasil dibuat. Cek email untuk konfirmasi, lalu masuk.",
    passwordLength: "Password harus tepat 8 karakter.",
    passwordMin: "Password harus tepat 8 karakter.",
    passwordRuleLength: "Tepat 8 karakter: 2 huruf kapital, 2 huruf kecil, 2 angka, 2 simbol",
    emailInvalid: "Masukkan alamat email yang valid.",
    passwordStrongRequired: "Password harus tepat 8 karakter: 2 huruf kapital, 2 huruf kecil, 2 angka, dan 2 simbol.",
    fillAllPasswordFields: "Silakan isi semua kolom password.",
    passwordDifferent: "Password baru harus berbeda dari password saat ini.",
    currentPasswordIncorrect: "Password saat ini salah.",
    passwordChangedSuccessfully: "Password berhasil diubah.",
    passwordMismatch:
      "Konfirmasi password tidak cocok.",
    invalidCredentials: "Email atau password salah.",
    passwordStrength: "Kekuatan password",
    weak: "Lemah",
    medium: "Sedang",
    strong: "Kuat",
    fairlyStrong: "Cukup Kuat",
    veryStrong: "Sangat Kuat",

    legacyResultBreakeven: "Impas",
    legacyTrades: "Trade",
    legacyDate: "Tanggal",
    legacyPeriod: "Periode",
    legacyLastMonth: "Bulan Lalu",
    legacyEquityCurve: "Kurva Equity",
    legacyDailyPnl: "P&L Harian",
    legacyPnlByPair: "P&L per Pair",
    legacyPsychologyAtEntry: "Psikologi Saat Entry",
    legacyTradeOutcome: "Hasil Trade",
    legacyDistributionResults: "Distribusi hasil trade Anda.",
    legacyCumulativePnl: "P&L kumulatif dari trade Anda.",
    legacyPnlEachDay: "P&L yang dihasilkan setiap hari trading.",
    legacyComparePairs: "Bandingkan performa antar pair trading.",
    legacyMindsetDistribution: "Distribusi trade berdasarkan kondisi psikologis, beserta persentase dan P&L.",
    legacyViewAllTrades: "Lihat semua trade yang tercatat di jurnal Anda.",
    legacyNoTrades: "Belum ada trade",
    legacyStartRecording: "Mulai mencatat trade untuk membangun jurnal Anda.",
    legacyUnknownAccount: "Akun Tidak Diketahui",
    legacyView: "Lihat",
    legacyBackToAllTrades: "Kembali ke Semua Trade",
    legacyTradeNotFound: "Trade tidak ditemukan",
    legacyTradeDoesNotExist: "Trade yang Anda cari tidak ada.",
    legacyCompleteTradeInfo: "Informasi lengkap mengenai trade ini.",
    legacyEntryExitRisk: "Level entry, exit, dan manajemen risiko.",
    legacyNoStrategy: "Belum ada strategi yang dicatat",
    legacyNoNotes: "Belum ada catatan untuk trade ini.",
    legacyCorePosition: "Informasi utama mengenai posisi.",
    legacyPriceResult: "Harga & Hasil",
    legacyExecutionOutcome: "Catat eksekusi dan hasil aktual.",
    legacyMindsetBefore: "Catat kondisi psikologis Anda sebelum trade dibuka.",
    legacyFutureReview: "Konteks tambahan untuk evaluasi di masa mendatang.",
    legacyWhatHappened: "Apa yang terjadi pada trade ini?",
    legacyDataManagement: "Manajemen Data",
    legacyExportBackup: "Ekspor laporan rapi atau cadangkan jurnal Anda ke Excel.",
    legacyPdfReport: "Laporan Performa PDF",
    legacyExcelWorkbook: "Workbook Excel",
    legacyPdfContents: "Isi PDF",
    legacyChooseReport: "Pilih apakah laporan menyertakan grafik visual dan seluruh log trade.",
    legacyIncludeCharts: "Sertakan grafik",
    legacyIncludeTradeLog: "Sertakan log trade",
    legacyExcelImport: "Impor Excel",
    legacyImportSheets: "Impor sheet Trades dan Accounts. Trade duplikat akan dilewati.",
    legacyChooseExcel: "Pilih file Excel",
    legacyReviewImport: "Tinjau Impor Excel",
    legacyImporting: "Mengimpor...",
    legacyImportData: "Impor Data",
    legacyAdjustPhoto: "Sesuaikan foto profil",
    legacyPhotoHint: "Kotak 1:1 • Geser untuk mengatur posisi • Cubit atau gunakan slider untuk memperbesar",
    legacyDragAdjust: "Geser untuk menyesuaikan",
    legacyZoom: "Zoom",    legacyBalanceMovementLower: "Pergerakan saldo",
    legacyMyTradingAccount: "Akun Trading Saya",
    legacyPsychologyDonutAria: "Diagram donut psikologi saat entry",
    legacyClose: "Tutup",
    legacyProfilePreview: "Pratinjau profil",

    legacyFailedSaveProfile: "Gagal menyimpan profil.",
    legacyProfileSaved: "Profil berhasil disimpan.",
    legacyNoImage: "Belum ada foto yang dipilih.",
    legacyImageTypes: "Hanya gambar JPG, PNG, dan WebP yang diperbolehkan.",
    legacyImageSize: "Ukuran foto profil harus kurang dari 2 MB.",
    legacyImageUrl: "Foto profil berhasil diunggah, tetapi URL publik tidak dapat dibuat.",
    legacyPhotoUpdated: "Foto profil berhasil diperbarui.",
    legacyUploadFailed: "Gagal mengunggah foto profil.",
    legacyCameraPermission: "Izin kamera ditolak. Silakan izinkan akses kamera di browser Anda.",
    legacyNoCamera: "Tidak ditemukan kamera pada perangkat ini.",
    legacyCameraBusy: "Kamera sedang digunakan oleh aplikasi lain.",
    legacyCaptureFailed: "Gagal mengambil foto.",
    legacyPhotoDeleted: "Foto profil berhasil dihapus.",
    legacyDeleteFailed: "Gagal menghapus foto profil.",
    legacyPasswordDifferent: "Password baru harus berbeda dari password saat ini.",
    legacyPasswordMismatch: "Password baru tidak cocok.",
    legacyCurrentPasswordIncorrect: "Password saat ini salah.",
    legacyPasswordChanged: "Password berhasil diubah.",

    "Account": "Akun",
    "Detail": "Detail",
    "Security": "Keamanan",
    "Recovery & Contact": "Pemulihan & Kontak",
    "Keep your backup contact information up to date.": "Pastikan informasi kontak cadangan Anda selalu terbaru.",
    "Backup Email": "Email Cadangan",
    "Only Gmail addresses ending in @gmail.com are accepted.": "Hanya alamat Gmail yang berakhiran @gmail.com yang diterima.",
    "Country": "Negara",
    "Phone / WhatsApp": "Telepon / WhatsApp",
    "Numbers only. Country code is selected separately.": "Hanya angka. Kode negara dipilih secara terpisah.",
    "Change Email": "Ganti Email",
    "Verify your current password before changing the sign-in email.": "Verifikasi password saat ini sebelum mengganti email login.",
    "Current Email": "Email Saat Ini",
    "New Gmail": "Gmail Baru",
    "Current Password": "Password Saat Ini",
    "Change Password": "Ganti Password",
    "Verify your current password before setting a new one.": "Verifikasi password saat ini sebelum membuat password baru.",
    "Password strength": "Kekuatan password",
    "Profile": "Profil",
    "Appearance": "Tampilan",
    "Data": "Data",
    "Trader name, journal name, and profile photo.": "Nama trader, nama jurnal, dan foto profil.",
    "Theme and automatic refresh preferences.": "Tema dan preferensi penyegaran otomatis.",
    "Password, email, backup email, and phone / WhatsApp.": "Password, email, email cadangan, dan telepon / WhatsApp.",
    "Data Management": "Manajemen Data",
    "Theme": "Tema",
    "Choose how PIPE.ID looks on your device.": "Pilih tampilan PIPE.ID di perangkat Anda.",
    "Light": "Terang",
    "Dark": "Gelap",
    "System": "Sistem",
    "Saving theme...": "Menyimpan tema...",
    "Theme preference": "Preferensi tema",
    "Your preference is saved to your account.": "Preferensi Anda disimpan ke akun Anda.",
    "Currently enabled.": "Saat ini aktif.",
    "Currently disabled.": "Saat ini nonaktif.",
    "On": "Aktif",
    "Off": "Nonaktif",
    "Auto Refresh": "Penyegaran Otomatis",
    "Automatically refresh journal data at a selected interval.": "Menyegarkan data jurnal secara otomatis pada interval yang dipilih.",
    "Enable Auto Refresh": "Aktifkan Penyegaran Otomatis",
    "Refresh Interval": "Interval Penyegaran",
    "15 seconds": "15 detik",
    "30 seconds": "30 detik",
    "1 minute": "1 menit",
    "5 minutes": "5 menit",
    "Saving...": "Menyimpan...",
    "Save Profile": "Simpan Profil",
    "Profile saved successfully.": "Profil berhasil disimpan.",
    "Failed to save profile.": "Gagal menyimpan profil.",
    "Profile Photo": "Foto Profil",
    "Change Photo": "Ganti Foto",
    "Take Photo": "Ambil Foto",
    "Choose from Gallery": "Pilih dari Galeri",
    "Delete Photo": "Hapus Foto",
    "Profile photo updated successfully.": "Foto profil berhasil diperbarui.",
    "Failed to upload profile photo.": "Gagal mengunggah foto profil.",
    "Profile photo removed successfully.": "Foto profil berhasil dihapus.",
    "Failed to remove profile photo.": "Gagal menghapus foto profil.",
    "Camera permission was denied. Please allow camera access in your browser.": "Izin kamera ditolak. Izinkan akses kamera di browser Anda.",
    "No camera was found on this device.": "Kamera tidak ditemukan di perangkat ini.",
    "Camera is already being used by another application.": "Kamera sedang digunakan aplikasi lain.",
    "Failed to capture photo.": "Gagal mengambil foto.",
    "Only JPG, PNG, and WebP images are allowed.": "Hanya gambar JPG, PNG, dan WebP yang diperbolehkan.",
    "Profile image must be smaller than 12 MB.": "Foto profil harus berukuran kurang dari 12 MB.",
    "No image selected.": "Belum ada foto yang dipilih.",
    "Close camera": "Tutup kamera",
    "Switch camera": "Ganti kamera",
    "Capture photo": "Ambil foto",
    "Uploading...": "Mengunggah...",
    "Upload": "Unggah",
    "Adjust profile photo": "Sesuaikan foto profil",
    "Zoom photo": "Perbesar foto",
    "Email must use lowercase letters and end in @gmail.com.": "Email harus menggunakan huruf kecil dan berakhiran @gmail.com.",
    "Registration successful. Check your email to confirm your account.": "Pendaftaran berhasil. Cek email Anda untuk mengonfirmasi akun.",
    "Loading trades...": "Memuat trade...",
    "WIN": "MENANG",
    "LOSS": "KALAH",
    "BREAKEVEN": "IMPAS",
    "Loss akan otomatis disimpan sebagai nilai negatif.": "Loss akan otomatis disimpan sebagai nilai negatif.",
    "Profit akan otomatis disimpan sebagai nilai positif.": "Profit akan otomatis disimpan sebagai nilai positif.",
    "Break-even otomatis disimpan sebagai 0.": "Break-even otomatis disimpan sebagai 0.",
    "Security contact information saved successfully.": "Informasi kontak keamanan berhasil disimpan.",
    "Email changed successfully.": "Email berhasil diubah.",
    "Failed to load security settings.": "Gagal memuat pengaturan keamanan.",
    "Backup email must use lowercase letters and end in @gmail.com.": "Email cadangan harus menggunakan huruf kecil dan berakhiran @gmail.com.",
    "Backup email must be different from your registered email.": "Email cadangan harus berbeda dari email terdaftar Anda.",
    "Phone / WhatsApp number must contain 11 to 12 digits.": "Nomor Telepon / WhatsApp harus terdiri dari 11 hingga 12 digit.",
    "New email must use lowercase letters and end in @gmail.com.": "Email baru harus menggunakan huruf kecil dan berakhiran @gmail.com.",
    "The new email is the same as your current email.": "Email baru sama dengan email Anda saat ini.",
    "The new email must be different from your backup email.": "Email baru harus berbeda dari email cadangan Anda.",
    "Enter your current password before changing your email.": "Masukkan password saat ini sebelum mengganti email.",
    "Current password": "Password saat ini",
    "New password": "Password baru",
    "Confirm new password": "Konfirmasi password baru",
    "Email": "Email",
    "Phone / WhatsApp must contain 11 to 12 digits.": "Telepon / WhatsApp harus terdiri dari 11 hingga 12 digit.",
    "Save Contact": "Simpan Kontak",
    "Update": "Perbarui",
    "Updating...": "Memperbarui...",
    "Use lowercase letters only and a Gmail address ending in @gmail.com.": "Gunakan huruf kecil dan alamat Gmail yang berakhiran @gmail.com.",
    "This is the same as your current email.": "Ini sama dengan email Anda saat ini.",
    "This email is already your backup email.": "Email ini sudah menjadi email cadangan Anda.",
    "Current password is required.": "Password saat ini wajib diisi.",
    "Failed to change password.": "Gagal mengubah password.",
    "Theme saved successfully.": "Tema berhasil disimpan.",
    "Failed to save theme.": "Gagal menyimpan tema.",
    "Trade": "Trade",
    "Trades": "Trade",
    "Unknown Account": "Akun Tidak Diketahui",
    "Unspecified": "Tidak Ditentukan",
    "BREAKEVEN": "Impas",
    "Trade with clarity.": "Trading dengan lebih jelas.",
    "Keep your trades, performance and psychology in one focused workspace.":
      "Simpan trade, performa, dan psikologi Anda dalam satu ruang kerja.",
    "Trading Journal · Private workspace":
      "PIPE.ID · Ruang kerja pribadi",
    "Loading trades...": "Memuat trade...",
    "Select an account to view journal data":
      "Pilih akun untuk melihat data jurnal",
    "Select an account first":
      "Pilih akun terlebih dahulu",
    "All Accounts": "Semua Akun",
    "All Pairs": "Semua Pair",
    "All Results": "Semua Hasil",
    "All Strategies": "Semua Strategi",
    "Create account before recording a trade.":
      "Buat akun terlebih dahulu sebelum mencatat trade.",
    "No trading account found":
      "Akun trading tidak ditemukan",
    "No account available":
      "Tidak ada akun tersedia",
    "Loading...": "Memuat...",
    "Trade not found.": "Trade tidak ditemukan.",
    "Trade not found": "Trade tidak ditemukan",
    "No notes recorded for this trade.":
      "Belum ada catatan untuk trade ini.",
    "Capture": "Ambil Foto",
    "Review Excel import": "Tinjau Impor Excel",
    "Cancel": "Batal",
    "Change": "Ubah",
    "Save": "Simpan",
    "Saving...": "Menyimpan..."
  }
};

function buildPhraseMap(language) {
  const map = {};
  const current = DICTIONARY[language];
  const other = DICTIONARY[language === "EN" ? "ID" : "EN"];
  Object.keys(current).forEach((key) => {
    const from = other[key];
    const to = current[key];
    if (from && to && from !== to) map[from] = to;
  });
  return map;
}

function translateDom(language) {
  if (typeof document === "undefined") return;
  const map = buildPhraseMap(language);
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  const nodes = [];
  let node;
  while ((node = walker.nextNode())) nodes.push(node);
  nodes.forEach((textNode) => {
    const parent = textNode.parentElement;
    if (!parent || ["SCRIPT", "STYLE", "NOSCRIPT"].includes(parent.tagName)) return;
    const raw = textNode.nodeValue;
    const trimmed = raw.trim();
    if (!trimmed) return;
    if (map[trimmed]) textNode.nodeValue = raw.replace(trimmed, map[trimmed]);
  });
  const elements = document.querySelectorAll("input[placeholder], textarea[placeholder], [title], [aria-label]");
  elements.forEach((el) => {
    ["placeholder", "title", "aria-label"].forEach((attr) => {
      const value = el.getAttribute(attr);
      if (value && map[value]) el.setAttribute(attr, map[value]);
    });
  });
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    if (typeof window === "undefined") return "EN";
    return localStorage.getItem("trading_journal_language") === "ID" ? "ID" : "EN";
  });

  function setLanguage(next) {
    const value = next === "ID" ? "ID" : "EN";
    setLanguageState(value);
    if (typeof window !== "undefined") localStorage.setItem("trading_journal_language", value);
    if (typeof document !== "undefined") document.documentElement.lang = value.toLowerCase();
  }

  useEffect(() => {
    if (typeof document === "undefined") return undefined;
    document.documentElement.lang = language.toLowerCase();
    let translating = false;
    const run = () => {
      if (translating) return;
      translating = true;
      try { translateDom(language); } finally { translating = false; }
    };
    run();
    const observer = new MutationObserver(() => run());
    observer.observe(document.body, { childList: true, subtree: true, characterData: true });
    return () => observer.disconnect();
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (key) => DICTIONARY[language]?.[key] ?? DICTIONARY.EN[key] ?? key,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

