import type { FastifyInstance } from "fastify";
import { dbQuery } from "../db/client.js";
import { requireUser } from "../auth.js";
import { createAccountSchema, transactionSchema, updateAccountSchema } from "../schemas.js";
const unauthorized=(reply:any)=>reply.status(401).send({error:{code:"UNAUTHORIZED",message:"Authentication required."}});
async function account(userId:string,id:string){return (await dbQuery<any>("select * from accounts where id=$1 and user_id=$2",[id,userId])).rows[0]}
async function detail(userId:string,id:string){const a=await account(userId,id);if(!a)return null;const b=await dbQuery<any>(`select a.starting_balance + coalesce((select sum(case when type='DEPOSIT' then amount else -amount end) from account_transactions where account_id=a.id),0) + coalesce((select sum(pnl) from trades where account_id=a.id),0) as current_balance from accounts a where a.id=$1 and a.user_id=$2`,[id,userId]);return {...a,current_balance:Number(b.rows[0]?.current_balance??a.starting_balance)}}
export async function accountRoutes(app:FastifyInstance){
app.get("/accounts",async(req,reply)=>{const id=await requireUser(req);if(!id)return unauthorized(reply);const r=await dbQuery<any>(`select a.*, a.starting_balance + coalesce((select sum(case when type='DEPOSIT' then amount else -amount end) from account_transactions where account_id=a.id),0) + coalesce((select sum(pnl) from trades where account_id=a.id),0) as current_balance from accounts a where a.user_id=$1 order by a.created_at desc`,[id]);return {data:r.rows.map(x=>({...x,current_balance:Number(x.current_balance)}))}});
app.post("/accounts",async(req,reply)=>{const id=await requireUser(req);if(!id)return unauthorized(reply);const p=createAccountSchema.safeParse(req.body);if(!p.success)return reply.status(400).send({error:{code:"VALIDATION_ERROR",message:p.error.issues[0]?.message||"Invalid request."}});const r=await dbQuery<any>("insert into accounts(user_id,name,account_type,starting_balance,currency,pair) values($1,$2,$3,$4,$5,$6) returning *",[id,p.data.name,p.data.accountType,p.data.startingBalance,p.data.currency,p.data.pair??null]);return reply.status(201).send({data:{...r.rows[0],current_balance:p.data.startingBalance}})});
app.get("/accounts/:id",async(req,reply)=>{const uid=await requireUser(req);if(!uid)return unauthorized(reply);const a=await detail(uid,(req.params as any).id);if(!a)return reply.status(404).send({error:{code:"ACCOUNT_NOT_FOUND",message:"Account not found."}});return {data:a}});
app.delete("/accounts/:id",async(req,reply)=>{const uid=await requireUser(req);if(!uid)return unauthorized(reply);const id=(req.params as any).id;const client=await (await import("../db/client.js")).pool?.connect();if(!client)return reply.status(503).send({error:{code:"DATABASE_UNAVAILABLE",message:"Database is not connected."}});try{await client.query("BEGIN");const a=await client.query("select id from accounts where id=$1 and user_id=$2 for update",[id,uid]);if(!a.rowCount){await client.query("ROLLBACK");return reply.status(404).send({error:{code:"ACCOUNT_NOT_FOUND",message:"Account not found."}})}await client.query("delete from account_transactions where account_id=$1 and user_id=$2",[id,uid]);await client.query("delete from trades where account_id=$1 and user_id=$2",[id,uid]);await client.query("delete from accounts where id=$1 and user_id=$2",[id,uid]);await client.query("COMMIT");return {ok:true}}catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}});
app.patch("/accounts/:id",async(req,reply)=>{const uid=await requireUser(req);if(!uid)return unauthorized(reply);const id=(req.params as any).id; if(!await account(uid,id))return reply.status(404).send({error:{code:"ACCOUNT_NOT_FOUND",message:"Account not found."}});const p=updateAccountSchema.safeParse(req.body);if(!p.success)return reply.status(400).send({error:{code:"VALIDATION_ERROR",message:p.error.issues[0]?.message||"Invalid request."}});const r=await dbQuery<any>("update accounts set name=coalesce($1,name),pair=case when $2 then $3 else pair end,updated_at=now() where id=$4 and user_id=$5 returning *",[p.data.name??null,Object.prototype.hasOwnProperty.call(p.data,"pair"),p.data.pair??null,id,uid]);return {data:await detail(uid,r.rows[0].id)}});
for(const [path,type] of [["deposit","DEPOSIT"],["withdraw","WITHDRAWAL"]] as const){app.post(`/accounts/:id/${path}`,async(req,reply)=>{const uid=await requireUser(req);if(!uid)return unauthorized(reply);const id=(req.params as any).id;const a=await detail(uid,id);if(!a)return reply.status(404).send({error:{code:"ACCOUNT_NOT_FOUND",message:"Account not found."}});const p=transactionSchema.safeParse(req.body);if(!p.success)return reply.status(400).send({error:{code:"VALIDATION_ERROR",message:p.error.issues[0]?.message||"Invalid amount."}});if(type==="WITHDRAWAL"&&p.data.amount>a.current_balance)return reply.status(400).send({error:{code:"INSUFFICIENT_BALANCE",message:"Withdrawal cannot exceed current balance."}});const r=await dbQuery<any>("insert into account_transactions(user_id,account_id,type,amount,note) values($1,$2,$3,$4,$5) returning *",[uid,id,type,p.data.amount,p.data.note??null]);return reply.status(201).send({data:r.rows[0],account:await detail(uid,id)})})}
app.get("/accounts/:id/transactions",async(req,reply)=>{const uid=await requireUser(req);if(!uid)return unauthorized(reply);const id=(req.params as any).id;if(!await account(uid,id))return reply.status(404).send({error:{code:"ACCOUNT_NOT_FOUND",message:"Account not found."}});const r=await dbQuery<any>("select * from account_transactions where account_id=$1 and user_id=$2 order by created_at desc",[id,uid]);return {data:r.rows}});
}
