import type { FastifyInstance } from "fastify";
import { randomBytes } from "node:crypto";
import { dbQuery } from "../db/client.js";
import { requireUser, getBearerToken } from "../auth.js";
import { createAccessToken, createRefreshToken, hashPassword, hashToken, refreshTtlSeconds, tokenTtlSeconds, verifyPassword, verifyToken } from "../security.js";
import { changeEmailSchema, changePasswordSchema, forgotPasswordSchema, loginSchema, refreshSchema, registerSchema, resetPasswordSchema } from "../schemas.js";
import { env } from "../config/env.js";
function err(reply:any,status:number,code:string,message:string){return reply.status(status).send({error:{code,message}})}
async function publicUser(id:string){const r=await dbQuery<any>("select id,email,created_at from users where id=$1",[id]);return r.rows[0]||null}
async function makeSession(userId:string){const access=createAccessToken(userId);const refresh=createRefreshToken(userId);const p=verifyToken(refresh)!;await dbQuery("insert into refresh_sessions(user_id,token_hash,expires_at) values($1,$2,to_timestamp($3))",[userId,hashToken(refresh),p.exp]);return {access_token:access,refresh_token:refresh,token_type:"Bearer",expires_in:tokenTtlSeconds,refresh_expires_in:refreshTtlSeconds}}
export async function authRoutes(app:FastifyInstance){
app.get("/auth/status",async(req,reply)=>{const id=await requireUser(req);if(!id)return err(reply,401,"UNAUTHORIZED","Authentication required.");return {authenticated:true,user:await publicUser(id)}});
app.post("/auth/register",async(req,reply)=>{const p=registerSchema.safeParse(req.body);if(!p.success)return err(reply,400,"VALIDATION_ERROR",p.error.issues[0]?.message||"Invalid request.");const exists=await dbQuery("select 1 from users where email=$1",[p.data.email]);if(exists.rowCount)return err(reply,409,"EMAIL_EXISTS","Email is already registered.");const hash=await hashPassword(p.data.password);const r=await dbQuery<any>("insert into users(email,password_hash) values($1,$2) returning id,email,created_at",[p.data.email,hash]);const u=r.rows[0];await dbQuery("insert into profiles(id,journal_name,theme) values($1,'Trading Journal','light')",[u.id]);return reply.status(201).send({user:u,session:await makeSession(u.id)});});
app.post("/auth/login",async(req,reply)=>{const p=loginSchema.safeParse(req.body);if(!p.success)return err(reply,400,"VALIDATION_ERROR",p.error.issues[0]?.message||"Invalid request.");const r=await dbQuery<any>("select id,email,password_hash,created_at from users where email=$1",[p.data.email]);if(!r.rowCount||!(await verifyPassword(p.data.password,r.rows[0].password_hash)))return err(reply,401,"INVALID_CREDENTIALS","Email or password is incorrect.");return {user:{id:r.rows[0].id,email:r.rows[0].email,created_at:r.rows[0].created_at},session:await makeSession(r.rows[0].id)};});
app.post("/auth/refresh",async(req,reply)=>{const p=refreshSchema.safeParse(req.body);if(!p.success)return err(reply,400,"VALIDATION_ERROR","Refresh token is required.");const payload=verifyToken(p.data.refreshToken);if(!payload||payload.type!=="refresh"||!payload.sub)return err(reply,401,"INVALID_REFRESH_TOKEN","Refresh token is invalid or expired.");const r=await dbQuery<any>("select id from refresh_sessions where user_id=$1 and token_hash=$2 and revoked_at is null and expires_at>now()",[payload.sub,hashToken(p.data.refreshToken)]);if(!r.rowCount)return err(reply,401,"INVALID_REFRESH_TOKEN","Refresh token is invalid or expired.");await dbQuery("update refresh_sessions set revoked_at=now() where id=$1",[r.rows[0].id]);return {session:await makeSession(payload.sub)};});
app.post("/auth/logout",async(req,reply)=>{const t=getBearerToken(req);if(t){const p=verifyToken(t);if(p?.sub) await dbQuery("update refresh_sessions set revoked_at=now() where user_id=$1 and revoked_at is null",[p.sub]);}return {ok:true}});
app.post("/auth/change-password",async(req,reply)=>{const id=await requireUser(req);if(!id)return err(reply,401,"UNAUTHORIZED","Authentication required.");const p=changePasswordSchema.safeParse(req.body);if(!p.success)return err(reply,400,"VALIDATION_ERROR",p.error.issues[0]?.message||"Invalid request.");const r=await dbQuery<any>("select password_hash from users where id=$1",[id]);if(!r.rowCount||!(await verifyPassword(p.data.currentPassword,r.rows[0].password_hash)))return err(reply,400,"CURRENT_PASSWORD_INVALID","Current password is incorrect.");await dbQuery("update users set password_hash=$1,updated_at=now() where id=$2",[await hashPassword(p.data.newPassword),id]);await dbQuery("update refresh_sessions set revoked_at=now() where user_id=$1 and revoked_at is null",[id]);return {ok:true}});
app.post("/auth/change-email",async(req,reply)=>{const id=await requireUser(req);if(!id)return err(reply,401,"UNAUTHORIZED","Authentication required.");const p=changeEmailSchema.safeParse(req.body);if(!p.success)return err(reply,400,"VALIDATION_ERROR",p.error.issues[0]?.message||"Invalid request.");const u=(await dbQuery<any>("select email,password_hash from users where id=$1",[id])).rows[0];if(!(await verifyPassword(p.data.password,u.password_hash)))return err(reply,400,"CURRENT_PASSWORD_INVALID","Current password is incorrect.");if(p.data.email===u.email)return err(reply,400,"EMAIL_SAME","New email must be different from current email.");const prof=(await dbQuery<any>("select backup_email from profiles where id=$1",[id])).rows[0];if(prof?.backup_email===p.data.email)return err(reply,400,"EMAIL_BACKUP_SAME","New email must be different from backup email.");if((await dbQuery("select 1 from users where email=$1 and id<>$2",[p.data.email,id])).rowCount)return err(reply,409,"EMAIL_EXISTS","Email is already registered.");await dbQuery("update users set email=$1,updated_at=now() where id=$2",[p.data.email,id]);await dbQuery("update refresh_sessions set revoked_at=now() where user_id=$1 and revoked_at is null",[id]);return {ok:true,user:await publicUser(id),session:await makeSession(id)}});
app.post("/auth/forgot-password",async(req,reply)=>{const p=forgotPasswordSchema.safeParse(req.body);if(!p.success)return err(reply,400,"VALIDATION_ERROR","A valid Gmail address is required.");const u=(await dbQuery<any>("select id from users where email=$1",[p.data.email])).rows[0];if(u){const raw=randomBytes(32).toString("hex");await dbQuery("delete from password_reset_tokens where user_id=$1 and used_at is null",[u.id]);await dbQuery("insert into password_reset_tokens(user_id,token_hash,expires_at) values($1,$2,now()+($3::int * interval '1 minute'))",[u.id,hashToken(raw),env.RESET_TOKEN_TTL_MINUTES]);if(env.NODE_ENV!=="production") return {ok:true,reset_token:raw,expires_in_minutes:env.RESET_TOKEN_TTL_MINUTES};}
return {ok:true,message:"If the account exists, recovery instructions will be sent."};});
app.post("/auth/reset-password",async(req,reply)=>{const p=resetPasswordSchema.safeParse(req.body);if(!p.success)return err(reply,400,"VALIDATION_ERROR",p.error.issues[0]?.message||"Invalid request.");const r=await dbQuery<any>("select id,user_id from password_reset_tokens where token_hash=$1 and used_at is null and expires_at>now()",[hashToken(p.data.token)]);if(!r.rowCount)return err(reply,400,"RESET_TOKEN_INVALID","Reset token is invalid or expired.");const uid=r.rows[0].user_id;await dbQuery("update users set password_hash=$1,updated_at=now() where id=$2",[await hashPassword(p.data.password),uid]);await dbQuery("update password_reset_tokens set used_at=now() where id=$1",[r.rows[0].id]);await dbQuery("update refresh_sessions set revoked_at=now() where user_id=$1 and revoked_at is null",[uid]);return {ok:true}});
}
