import type { FastifyInstance } from "fastify";
import { dbQuery } from "../db/client.js";
import { requireUser } from "../auth.js";
import { createTradeSchema, tradeListQuerySchema, updateTradeSchema } from "../schemas.js";
const err=(reply:any,s:number,c:string,m:string)=>reply.status(s).send({error:{code:c,message:m}});
async function ownAccount(uid: string, id: string) {const result = await dbQuery("select 1 from accounts where id=$1 and user_id=$2",[id, uid]);return (result.rowCount ?? 0) > 0;}
export async function tradeRoutes(app:FastifyInstance){
app.get("/trades",async(req,reply)=>{const uid=await requireUser(req);if(!uid)return err(reply,401,"UNAUTHORIZED","Authentication required.");const p=tradeListQuerySchema.safeParse(req.query);if(!p.success)return err(reply,400,"VALIDATION_ERROR",p.error.issues[0]?.message||"Invalid query.");const q=p.data;const where=["t.user_id=$1"];const vals:any[]=[uid];let n=2; if(q.accountId){if(!await ownAccount(uid,q.accountId))return err(reply,404,"ACCOUNT_NOT_FOUND","Account not found.");where.push(`t.account_id=$${n++}`);vals.push(q.accountId)}if(q.pair){where.push(`lower(t.pair)=lower($${n++})`);vals.push(q.pair)}if(q.result){where.push(`t.result=$${n++}`);vals.push(q.result)}if(q.psychology){where.push(`t.psychology=$${n++}`);vals.push(q.psychology)}if(q.from){where.push(`t.trade_date>=$${n++}`);vals.push(q.from)}if(q.to){where.push(`t.trade_date<=$${n++}`);vals.push(q.to)}const count=await dbQuery<any>(`select count(*)::int as total from trades t where ${where.join(" and ")}`,vals);const total=count.rows[0].total;const offset=(q.page-1)*q.limit;const rows=await dbQuery<any>(`select t.*,a.name as account_name,a.currency as account_currency,a.account_type from trades t left join accounts a on a.id=t.account_id and a.user_id=t.user_id where ${where.join(" and ")} order by t.trade_date desc,t.created_at desc limit $${n++} offset $${n++}`,[...vals,q.limit,offset]);return {data:rows.rows,pagination:{page:q.page,limit:q.limit,total,total_pages:Math.ceil(total/q.limit)}}});
app.post("/trades",async(req,reply)=>{const uid=await requireUser(req);if(!uid)return err(reply,401,"UNAUTHORIZED","Authentication required.");const p=createTradeSchema.safeParse(req.body);if(!p.success)return err(reply,400,"VALIDATION_ERROR",p.error.issues[0]?.message||"Invalid trade.");if(!await ownAccount(uid,p.data.accountId))return err(reply,404,"ACCOUNT_NOT_FOUND","Selected account was not found.");const d=p.data;const r=await dbQuery<any>(`insert into trades(user_id,account_id,trade_date,pair,direction,entry_price,exit_price,stop_loss,take_profit,lot_size,result,pnl,strategy,session,notes,psychology,risk_reward) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) returning *`,[uid,d.accountId,d.tradeDate.toISOString().slice(0,10),d.pair,d.direction,d.entryPrice,d.exitPrice??null,d.stopLoss??null,d.takeProfit??null,d.lotSize,d.result,d.pnl,d.strategy??null,d.session??null,d.notes??null,d.psychology,d.riskReward??null]);return reply.status(201).send({data:r.rows[0]})});
app.delete("/trades/:id",async(req,reply)=>{const uid=await requireUser(req);if(!uid)return err(reply,401,"UNAUTHORIZED","Authentication required.");const id=(req.params as any).id;const r=await dbQuery("delete from trades where id=$1 and user_id=$2 returning id",[id,uid]);if(!r.rowCount)return err(reply,404,"TRADE_NOT_FOUND","Trade not found.");return {ok:true}});
app.get("/trades/:id",async(req,reply)=>{const uid=await requireUser(req);if(!uid)return err(reply,401,"UNAUTHORIZED","Authentication required.");const r=await dbQuery<any>("select t.*,a.name as account_name,a.currency as account_currency,a.account_type from trades t left join accounts a on a.id=t.account_id and a.user_id=t.user_id where t.id=$1 and t.user_id=$2",[(req.params as any).id,uid]);if(!r.rowCount)return err(reply,404,"TRADE_NOT_FOUND","Trade not found.");return {data:r.rows[0]}});
app.patch("/trades/:id",async(req,reply)=>{const uid=await requireUser(req);if(!uid)return err(reply,401,"UNAUTHORIZED","Authentication required.");const id=(req.params as any).id;if(!(await dbQuery("select 1 from trades where id=$1 and user_id=$2",[id,uid])).rowCount)return err(reply,404,"TRADE_NOT_FOUND","Trade not found.");const p=updateTradeSchema.safeParse(req.body);if(!p.success)return err(reply,400,"VALIDATION_ERROR",p.error.issues[0]?.message||"Invalid trade.");const d=p.data;const existing=(await dbQuery<any>("select result,pnl from trades where id=$1 and user_id=$2",[id,uid])).rows[0];const merged={result:d.result??existing.result,pnl:d.pnl??Number(existing.pnl)};const invariant=createTradeSchema.pick({result:true,pnl:true}).safeParse(merged);if(!invariant.success)return err(reply,400,"VALIDATION_ERROR",invariant.error.issues[0]?.message||"Result and PnL do not match.");const fields:any[]=[];const vals:any[]=[];let n=1;const add=(column:string,value:any)=>{fields.push(`${column}=$${n++}`);vals.push(value)};if(d.tradeDate!==undefined)add("trade_date",d.tradeDate.toISOString().slice(0,10));if(d.pair!==undefined)add("pair",d.pair);if(d.direction!==undefined)add("direction",d.direction);if(d.entryPrice!==undefined)add("entry_price",d.entryPrice);if(d.exitPrice!==undefined)add("exit_price",d.exitPrice);if(d.stopLoss!==undefined)add("stop_loss",d.stopLoss);if(d.takeProfit!==undefined)add("take_profit",d.takeProfit);if(d.lotSize!==undefined)add("lot_size",d.lotSize);if(d.result!==undefined)add("result",d.result);if(d.pnl!==undefined)add("pnl",d.pnl);if(d.strategy!==undefined)add("strategy",d.strategy);if(d.session!==undefined)add("session",d.session);if(d.notes!==undefined)add("notes",d.notes);if(d.psychology!==undefined)add("psychology",d.psychology);if(d.riskReward!==undefined)add("risk_reward",d.riskReward);add("updated_at",new Date());if(!fields.length)return {data:(await dbQuery<any>("select * from trades where id=$1 and user_id=$2",[id,uid])).rows[0]};vals.push(id,uid);const r=await dbQuery<any>(`update trades set ${fields.join(",")} where id=$${n++} and user_id=$${n++} returning *`,vals);return {data:r.rows[0]}});
}
